# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  - go mod download
builds:
- main: cmd/gencert/generate_cert.go
  binary: gencert
  id: "gencert"
  goos:
       - windows
       - linux
       - darwin
  goarch:
       - 386
       - amd64
       - arm
       - arm64
- main: cmd/reloadCerts/main.go
  binary: reloadCerts
  id: "reloadCerts"
  goos:
       - windows
       - linux
       - darwin
  goarch:
       - 386
       - amd64
       - arm
       - arm64
- env:
  - CGO_ENABLED=0
archives:
  - id: "TLSWebServer"
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os  }}_{{ .Arch  }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - AutomaticCertRenewal.md
      - config.yml
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
